DWAPlannerROS:
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_th: 3.2
  max_vel_trans: 0.55
  min_vel_trans: 0.1
  max_vel_x: 0.55
  min_vel_x: -0.55
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 1.0
  min_rot_vel: 0.4
  
  
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: true
  
  oscillation_reset_dist: 0.05
  
  prune_plan: true
