global_costmap:
  global_frame: map
  robot_base_frame: dummy
  update_frequency: 5 #5.0 #1
  publish_frequency: 5 #5.0 #1
 
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




