local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 25.0
  publish_frequency: 20.0
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05
  transform_tolerance: 1.0
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}