local_costmap:
  # global_frame: odom
  global_frame: map
  robot_base_frame: dummy
  transform_tolerance: 0.5

  update_frequency: 25.0
  publish_frequency: 20.0 

  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}